# Generated by Django 5.0.6 on 2024-06-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, null=True)),
                ('order_date', models.DateField(null=True)),
                ('quantity', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('customer_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.customer')),
                ('product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.product')),
            ],
        ),
    ]
